# The base image is the image that is used to build the Dockerfile.
FROM nginx:1.21

# NOTE: this Dockerfile is completely unnecessary.
# We are not customizing the nginx image at all.
# It is included just to be consistent with the other examples.

# This will run the nginx process
CMD ["nginx", "-g", "daemon off;"]
